### ISSUE TITLE
LoginFragment duplicate code

### ISSUE THREAD

**Issue by lukasl66** [AOEpeople/meals-android#10]
https://github.com/AOEpeople/meals-android/blob/3283db96923468abaafaac409a2a96d86155bce6/app/src/main/java/com/aoe/mealsapp/LoginFragment.java#L108

Sowohl die SharedPreferences als auch die EditTexts holst du dir doch oben schon. Du kannst doch dieselben Instanzen verwenden?

**Comment by TobiasUhmann** [comment]
Stimmt. Außerdem steht zu viel Code in onCreateView(). Ich habe die anonyme Klasse ausgelagert und die EditTexts als Felder der Klasse deklariert.
