### ISSUE TITLE
Mehrere SharedPreference commits

### ISSUE THREAD

**Issue by lukasl66** [AOEpeople/meals-android#11]
https://github.com/AOEpeople/meals-android/blob/3283db96923468abaafaac409a2a96d86155bce6/app/src/main/java/com/aoe/mealsapp/LoginFragment.java#L113

`commits` blockieren den UI Thread und sollten deshalb sparsam verwendet werden. Da du ein paar Zeilen weiter unten sowieso schon commit aufrufst, kannst du dir dieses hier sparen.

**Comment by TobiasUhmann** [comment]
Hab das commit() durch apply() ersetzt. Damit wird das Speichern im Hintergrund durchgeführt.
