### ISSUE TITLE
CREDENTIALS_WERE_VALIDATED

### ISSUE THREAD

**Issue by lukasl66** [AOEpeople/meals-android#12]
https://github.com/AOEpeople/meals-android/blob/3283db96923468abaafaac409a2a96d86155bce6/app/src/main/java/com/aoe/mealsapp/WebFragment.java#L312

Werden die Werte überhaupt irgendwo gelesen?

**Comment by TobiasUhmann** [comment]
Nein. Das ist noch Code der nötig war als die Login-Activity vor der Web-Activity aufgerufen wurde und ist nicht mehr nötig. Hab ich entfernt.
