### ISSUE TITLE
null alarm manager?

### ISSUE THREAD

**Issue by lukasl66** [AOEpeople/meals-android#13]
https://github.com/AOEpeople/meals-android/blob/3283db96923468abaafaac409a2a96d86155bce6/app/src/main/java/com/aoe/mealsapp/SettingsFragment.java#L116

Kann der Alarm Manager überhaupt null sein?

**Comment by TobiasUhmann** [comment]
Ich vermute nicht. Hab nochmal die Doku durchgesehen, aber kein Hinweis darauf ob null zurückkommen könnte oder nicht.

Ein assert alarmManager != null ist mir aber doch zu riskant. Ich belass es beim Runtime-Check.
