### ISSUE TITLE
duplicate code BootReceiver

### ISSUE THREAD

**Issue by lukasl66** [AOEpeople/meals-android#14]
https://github.com/AOEpeople/meals-android/blob/3283db96923468abaafaac409a2a96d86155bce6/app/src/main/java/com/aoe/mealsapp/BootReceiver.java#L35

Derselbe lange Block für das Auslesen der Uhrzeit wird auch schon im SettingsFragment verwendet. Da lohnt sich schon eine Helper Klasse.

Bringt es eigtl. irgendwelche Vorteile, die Uhrzeit aus der properties Datei auszulesen? Wenn man die Uhrzeit statisch in einer Klasse setzen würde, würde man sich das Parsen sparen und ggf. auch etwas Calendar-Kram.

**Comment by TobiasUhmann** [comment]
Ja, ne Helper-Klasse muss hier definitiv her. Dafür wird sogar ein util-Package spendiert.
