### ISSUE TITLE
Erinnerung Unhappy Path

### ISSUE THREAD

**Issue by lukasl66** [AOEpeople/meals-android#15]
https://github.com/AOEpeople/meals-android/blob/3283db96923468abaafaac409a2a96d86155bce6/app/src/main/java/com/aoe/mealsapp/AlarmReceiver.java#L68

Wenn der Nutzer beim Alaram gerade offline ist, bekommt er keine Notification für den nächsten Tag. Lösung könnte sein, den Alarm auf eine spätere Zeit zu setzen, um es erneut zu versuchen.

**Comment by TobiasUhmann** [comment]
Hab das Problem in eb993049fba2db035af0b89ca61b73f568666c61 jetzt so gelöst, dass der Code es innerhalb einer Stunde alle 5 Minuten erneut versucht. Muss ich jetzt noch testen.
