### ISSUE TITLE
TaskStackBuilder

### ISSUE THREAD

**Issue by lukasl66** [AOEpeople/meals-android#18]
https://github.com/AOEpeople/meals-android/blob/3283db96923468abaafaac409a2a96d86155bce6/app/src/main/java/com/aoe/mealsapp/AlarmReceiver.java#L329

Wofür braucht man den?

**Comment by TobiasUhmann** [comment]
Es gibt zwei Arten eine Activity zu starten wenn man auf eine Notification klickt:

- eine normale Activity zu der der User navigieren könnte, die eventuell schon im Hintergrund liegt
- eine spezielle Activity zu der der User sonst nicht navigieren könnte

(siehe https://developer.android.com/training/notify-user/Navigation)

Die App verwendet die erste Variante. Falls die Activity bereits im Hintergrund existiert (weil sie zuvor per Home-Button geschlossen wurde) soll sie geöffnet werden und sich so verhalten als wäre der User dorthin navigiert. Dazu zählt auch die Back-Button-Navigation die einen korrekt erstellten BackStack voraussetzt.

Der Code befindet sich jetzt in Notifications.showMealsNotification().

**Comment by lukasl66** [comment]
Wobei man im konkreten Fall keine Up-Navigation hat, weil es sich um die Main Activity handelt oder? Weil sich das aber ändern könnte, finde ich deine Lösung aber sauberer.
