### ISSUE TITLE
Groooße Klasse...

### ISSUE THREAD

**Issue by lukasl66** [AOEpeople/meals-android#19]
https://github.com/AOEpeople/meals-android/blob/3283db96923468abaafaac409a2a96d86155bce6/app/src/main/java/com/aoe/mealsapp/AlarmReceiver.java#L1

Vor allem im Alarm Receiver fällt mir auf, dass viele unterschiedliche Funktionalitäten separieren könnte (und sollte), die aktuell über den ganzen Code verteilt ist: API Requests, Json Parsing... Da lohnen sich zum Teil definitiv schon eigene Klassen. Vereinfacht das Verständnis, ist besser test- und wartbar.

**Comment by TobiasUhmann** [comment]
Extracted the logic that accesses the default SharedPreferences to read and write Settings:

https://github.com/AOEpeople/meals-android/commit/44e54a3aca42367112d2d4a76eadcced71550a44

**Comment by TobiasUhmann** [comment]
Extracted the Server communication and JSON parsing Code into a Kotlin wrapper for the JSON API (that uses Moshi to parse JSON).

https://github.com/AOEpeople/meals-android/commit/3d0c1a4cd2242ecd069e8409088b244a412e256e
