### ISSUE TITLE
Absoluter Pfad in build.gradle

### ISSUE THREAD

**Issue by lukasl66** [AOEpeople/meals-android#2]
https://github.com/AOEpeople/meals-android/blob/3283db96923468abaafaac409a2a96d86155bce6/app/build.gradle#L14

Vielleicht musst du auch gar keinen Debug Keystore selbst erstellen, sondern kannst es so lösen wie hier? https://stackoverflow.com/a/35035828

**Comment by TobiasUhmann** [comment]
Ja, hat funktioniert! Hatte zwar vorher auch den existierenden Debug-Keystore benutzt, aber so ist es wesentlich besser lesbar.

Netter Nebeneffekt: Im SO-Thread wird auch geklärt warum der Debugger gesponnen hat: Die deploy Build Variant ist nicht als debuggable deklariert. Eigentlich muss sie das auch gar nicht sein. Hab Gradle entsprechend angepasst und den server URL workaround wieder rausgenommen.
