### ISSUE TITLE
SharedPreferenceKeys

### ISSUE THREAD

**Issue by lukasl66** [AOEpeople/meals-android#20]
https://github.com/AOEpeople/meals-android/blob/3283db96923468abaafaac409a2a96d86155bce6/app/src/main/java/com/aoe/mealsapp/SharedPreferenceKeys.java#L6

Der Aufbau scheint mir unnötig kompliziert, aber lass da mal drüber reden. Was ich auf jeden Fall irritierend finde, ist, dass die Keys und Values gemischt sind, obwohl die Klasse SharedPreference**Keys** heißt.

**Comment by TobiasUhmann** [comment]
Ja, die Namenskonvention war auf jeden Fall verwirrend. Es erschien mir anfangs als die simpelste Lösung die Namen der XML-Strings die die Settings in XML referenzieren ebenfalls als Werte für die Persistierung in den SharedPreferences zu verwenden. Doch dann kommt er zu der verwirrenden Namenskolision zwischen "Key" und "Value" wie sie in XML bzw. den SharedPreferences verwendet werden.

Darum verwende ich als Werte jetzt die Namen der Enums die im Code verwendet werden. Sie sind außerdem kürzer und erleichtern das Debuggen. Vor allem ist keine Zuordnung zwischen Enum und persistiertem String mehr nötig. Das macht den Code wesentlich kürzer und lesbarer. Man darf bloß nicht mehr einfach Enum-Namen ändern, weil es sonst zu Problemen beim Lesen alter SharedPreferences kommt.

Die Änderung ist Teil des Refactorings der AlarmReceiver Klasse gewesen.
