### ISSUE TITLE
super.onBackPressed

### ISSUE THREAD

**Issue by lukasl66** [AOEpeople/meals-android#3]
https://github.com/AOEpeople/meals-android/blob/3283db96923468abaafaac409a2a96d86155bce6/app/src/main/java/com/aoe/mealsapp/MainActivity.java#L49

Den Teil verstehe ich nicht. Wieso muss noch was gemacht werden, wenn super.onBackPressed sowieso schon aufgerufen wurde?

**Comment by TobiasUhmann** [comment]
Normalerweise ist das initiale Fragment nicht auf dem Fragment Back Stack, sodass die Activity beim ersten super.onBackPressed() beendet würde. Um das Fragment über onBackPressed() benachrichtigen zu können muss es auf dem Back Stack liegen. Das erste super.onBackPressed() führt dann nur zum Entferenen des Fragments was eine leere Activity hinterlässt. super.onBackPressed() muss dann ein zweites Mal aufgerufen werden um die Activity zu beenden.

**Comment by TobiasUhmann** [comment]
So, hab das jetzt aber optimiert. Statt das letzte Fragment zu entfernen und schließlich die Activity zu beenden wird die Activity jetzt per finish() beendet falls nur noch ein Fragment auf dem Stack liegt.

**Comment by lukasl66** [comment]
Ah alles klar. Code ist jetzt besser verständlich! 👍
