### ISSUE TITLE
fragment tag

### ISSUE THREAD

**Issue by lukasl66** [AOEpeople/meals-android#4]
https://github.com/AOEpeople/meals-android/blob/3283db96923468abaafaac409a2a96d86155bce6/app/src/main/java/com/aoe/mealsapp/MainActivity.java#L93

Bei dem Fragment oben gibst du ein Tag mit, hier nicht. Gibt es dafür einen Grund?

**Comment by TobiasUhmann** [comment]
Ja, das LoginFragment implementiert OnBackPressedListener nicht und braucht daher kein Tag um für die Benachrichtigung gefunden zu werden. Daher sollte dem BackStackEntry in der folgenden Zeile allerdings auch kein Name gegeben werden.
