### ISSUE TITLE
AppCompatActivity cast

### ISSUE THREAD

**Issue by lukasl66** [AOEpeople/meals-android#5]
https://github.com/AOEpeople/meals-android/blob/3283db96923468abaafaac409a2a96d86155bce6/app/src/main/java/com/aoe/mealsapp/WebFragment.java#L101

Den Cast würde ich so machen, wie du es schon in `onAttach` gemacht hast. Erst den Typ überprüfen und dann casten oder eine aussagekräftige Exception werfen. Am besten in `onActivityAttached`.

**Comment by TobiasUhmann** [comment]
Ja, stimmt. Ich denke eine explizite Exception ist hier die richtige Wahl. Fragmente sollten ja eigentlich wiederverwendbar sein. Würde man dieses Fragment an eine nicht-AppCompatActivity anhängen käme es zum Absturz durch eine ClassCastException. Eine aussagekräftigere Exception ist da wohl der bessere Weg. Zusammen mit einer JavaDoc-Anmerkung, dass dieses Fragment eine AppCompatActivity voraussetzt.
