### ISSUE TITLE
initWebView

### ISSUE THREAD

**Issue by lukasl66** [AOEpeople/meals-android#6]
https://github.com/AOEpeople/meals-android/blob/3283db96923468abaafaac409a2a96d86155bce6/app/src/main/java/com/aoe/mealsapp/WebFragment.java#L311

Wieso nicht `if(url.equals(PAGE_LOGIN))`?

**Comment by TobiasUhmann** [comment]
An der Stelle will ich lieber prüfen ob, dass ich auf keiner gültigen Seite gelandet bin statt auf der ungültigen um den Fall vorzubeugen, dass es eine neue Fehlerseite gibt / geben wird auf die man gelangt, die dann nicht erkannt wird. Dann würde man auf der Fehlerseite bleiben.
