### ISSUE TITLE
duplicate login code

### ISSUE THREAD

**Issue by lukasl66** [AOEpeople/meals-android#7]
https://github.com/AOEpeople/meals-android/blob/3283db96923468abaafaac409a2a96d86155bce6/app/src/main/java/com/aoe/mealsapp/WebFragment.java#L204

Sieht mir nach duplicate code aus, siehe `loadLoginPage`. Da kann doch bestimmt einiges zusammengefasst werden.

**Comment by TobiasUhmann** [comment]
Diesen Teil konnte ich leider nicht zusammenfassen. Der Versuch den Code in onCreateView() durch Abänderung von dem im onResume() weglassen zu können schlug fehl. 

Jedoch ist dabei aufgefallen, dass der OnSharedPreferencesChangedListener in WebFragment überflüssig war (siehe Commit Message).

**Comment by lukasl66** [comment]
Schlug das fehl bevor oder oder nachdem wir gestern über eine mögliche Lösung gesprochen haben?

**Comment by TobiasUhmann** [comment]
Nach dem Besprechen der Lösung. Ich hatte auch zwischenzeitlich die leeren Strings als Default-Werte beim Lesen der SharedPreferences angegeben und die folgenden ?: Ausdrücke entsprechend vereinfacht.

Aber dann kam beim ersten Laden das Problem auf, dass sich die Sprache der Seite geändert hat, weil der erste Check ergab, dass sich die Sprache geändert hätte (null -> irgendwas). Statt hier eine Behandlung für den Spezialfall einzubauen, dass die Seite gerade das erste mal geladen wird hab ich lieber das einmalig doppelte Lesen der SharedPreferences in onCreateView.

**Comment by lukasl66** [comment]
`
@Override
    public void onResume() {
        super.onResume();

        SharedPreferences defaultSharedPreferences = PreferenceManager.getDefaultSharedPreferences(getContext());

        String preferenceUsername = defaultSharedPreferences.getString(SharedPreferenceKeys.USERNAME, "");
        String preferencePassword = defaultSharedPreferences.getString(SharedPreferenceKeys.PASSWORD, "");
        String preferenceLanguage = defaultSharedPreferences.getString(SharedPreferenceKeys.LANGUAGE, null);

        assert preferenceLanguage != null;

        boolean updateUsername = !preferenceUsername.equals(lastUsername);
        boolean updatePassword = !preferencePassword.equals(lastPassword);
        boolean updateLanguage = (lastLanguage != null) && !preferenceLanguage.equals(lastLanguage);
      
        lastUsername = preferenceUsername;
        lastPassword = preferencePassword;
        lastLanguage = preferenceLanguage;

       ...
}
`

Vielleicht irgendwie so?

**Comment by TobiasUhmann** [comment]
Ja, das würde funktionieren. Damit würde man sich die drei Lesezugriffe beim erstmaligen Laden sparen. Dennoch würde ich den Code so belassen.

Ich möchte den Check ob sich die SharedPreferences geändert haben von der Wahl der Default-Werte für die Server-Anfrage trennen. Der Code der prüft ob sich die SharedPreferences geändert haben ist in dieser Form allgemein verwendbar (z.B. auch bei Key-Value-Pairs bei denen man zwischen null und "" unterscheiden möchte). Man könnte ihn in dieser Form wiederverwenden und müsste nicht auf situationsabhängige Default-Werte achten.

Abgesehen von der Nicht-Unterscheidbarkeit von tatsächlich gelesen Werten mag ich die Default-Werte nicht, weil man prinzipiell darauf achten muss überall die gleichen Default-Werte zu verwenden. Da hatte ich mal viel Zeit ins Debugging investiert weil ich einen Default-Wert nicht angepasst hatte. Das wäre in diesem Fall wohl kein Problem, weil es nur diese Stelle im Code gibt - aber vielleicht kommt später eine dazu.

Schließlich wollte ich die Semantik der Variablen die die zuletzt gelesenen SharedPreference-Werte speichern möglichst einfach halten. Beispielsweise soll lastUsername den zuletzt gelesenen Benutzernamen speichern. Wenn der null war soll null gespeichert werden und nicht "" weil dieser später bei fehlendem Benutzernamen an den Server geschickt wird.

Im Großen und Ganzen will ich also diesen ganzen "Prüfe ob sich die SharedPreferences geändert haben"-Mechanismus möglichst wiederverwendbar halten. Nebenbei würde ich den Code zum erstmaligen Laden der Seite in onCreateView() erwarten. Dass die initiale Seite geladen wird, weil sich der Default-Wert von Feldern (null) vom Default-Wert beim Laden der SharedPreferences ("") unterscheidet finde ich nicht so intuitiv.

Ich muss aber zugeben, dass mir dieser dicke Code-Block in onResume() auch nicht gefällt. Ich überlege wie ich den da weg kriege ohne unnötige Lesezugriffe auf die SharedPreferences einzubauen.

**Comment by TobiasUhmann** [comment]
So. Der Code in onResume() ist jetzt deutlich kürzer und lesbarer. Der Zugriff auf die SharedPreferences und der Vergleich von vorher und nachher erfolgt jetzt in privaten Helper-Methoden.

onResume() gefällt mir jetzt gut. Aber man erkennt deutlich die Code-Redundanz zwischen den Helper-Methoden. Ich hab probiert eine generische Lösung zu implementieren: Ein "CachedSharedPreferences" Objekt das den letzten Stand der Preferences enthält die diese Activity benötigt und per update() prüft ob sich diese geändert haben. Da dann aber nach 45min noch nicht fertig war und während dem Implementieren noch einige offene Fragen auftauchten und die jetzige Lösung funktioniert hab ich's erst Mal liegen lassen.
