### ISSUE TITLE
switch website language

### ISSUE THREAD

**Issue by lukasl66** [AOEpeople/meals-android#8]
https://github.com/AOEpeople/meals-android/blob/3283db96923468abaafaac409a2a96d86155bce6/app/src/main/java/com/aoe/mealsapp/WebFragment.java#L221

Die Zeile wird nicht durchlaufen, wenn man sich Username UND Language geändert haben.

**Comment by TobiasUhmann** [comment]
Gefixt. Ändern sich Credentials und Sprache wird jetzt die Menü Webseite in der neuen Sprache geladen.

**Comment by lukasl66** [comment]
👍
