### ISSUE TITLE
SharedPreferenceListener noch benötigt?

### ISSUE THREAD

**Issue by lukasl66** [AOEpeople/meals-android#9]
https://github.com/AOEpeople/meals-android/blob/3283db96923468abaafaac409a2a96d86155bce6/app/src/main/java/com/aoe/mealsapp/WebFragment.java#L31

Brauchst du den noch, jetzt wo die Shared Preferences in onResume gelesen werden?

**Comment by TobiasUhmann** [comment]
Ne, denke der ist nicht mehr nötig. Die Idee war auf Änderungen in den SharedPreferences zu horchen die passieren während die Activity läuft. Das sollte in der App aber nicht möglich sein.

Zumindest hat auf meine StackOverflow Frage hier niemand mit "Doch" geantwortet:

https://stackoverflow.com/questions/49674787/onsharedpreferencechangelistener-useful-outside-activity-that-changes-sharedpref

Hab die Listener-Implementierung daher entfernt.

**Comment by lukasl66** [comment]
@TobiasUhmann, gibts dazu einen Commit?

**Comment by lukasl66** [comment]
Hab den Commit gefunden!
